# Generated by Django 5.0.4 on 2024-05-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_alter_job_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
