# Generated by Django 5.0.4 on 2024-05-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='ContactUs',
        ),
    ]
